Alias /abraflexi-api-doc-en /usr/share/doc/abraflexi-api-doc-en/html

<Directory /usr/share/doc/abraflexi-api-doc-en/html>
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
    DirectoryIndex index.html
</Directory>
